CinemaDemo/Controllers/ApprovalsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CinemaDemo.Models.Approvals;

namespace CinemaDemo.Controllers
{
    /// <summary>
    /// Chain of responsibility pattern
    /// https://www.dofactory.com/net/chain-of-responsibility-design-pattern
    /// </summary>
    public class ApprovalsController : Controller
    {
        
        public ActionResult Index()
        {
            Approver directorLarry = new Director(); //<10000K
            Approver vicePresidentSam = new VicePresident();//<25000
            Approver presidentTammy = new President();//<100000

            //Set the chain
            directorLarry.SetSuccessor(vicePresidentSam);
            vicePresidentSam.SetSuccessor(presidentTammy);

            // Generate and process purchase requests
            Purchase p1 = new Purchase(2034, 350.00, "Assets");
            directorLarry.ProcessRequest(p1);

            Purchase p2 = new Purchase(2035, 32590.10, "Project X");
            directorLarry.ProcessRequest(p2);

            Purchase p3 = new Purchase(2036, 122100.00, "Project Y");
            directorLarry.ProcessRequest(p3);

            Purchase p4 = new Purchase(2037, 122100.00, "Project Z");
            presidentTammy.ProcessRequest(p4);

            return View();
        }

        // GET: ApprovalsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ApprovalsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ApprovalsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApprovalsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ApprovalsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ApprovalsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ApprovalsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CinemaDemo/Controllers/CinemaController.cs
using CinemaDemo.Factories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaDemo.Controllers
{
    public class CinemaController : Controller
    {
        public IConfiguration Configuration { get; }

        private FilmFactory _factory { get; set; }

        private string _connectionString { get; set; }

        public CinemaController(IConfiguration configuration)
        {
            Configuration = configuration;
            _connectionString = Configuration["ConnectionStrings:DefaultConnection"];
            _factory = new FilmFactory(_connectionString);
        }

        // GET: CinemaController
        public ActionResult Index()
        {

            var viewModel = _factory.GetFilmShowings();

            return View(viewModel);
        }

        // GET: CinemaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CinemaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CinemaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CinemaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CinemaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CinemaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CinemaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CinemaDemo/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CinemaDemo.Models.EmployeeModels;

namespace CinemaDemo.Controllers
{
    /// <summary>
    /// Composite Design Pattern
    /// </summary>
    public class EmployeeController : Controller
    {
        /// <summary>
        /// Employee Controller
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            Employee Rahul = new Employee { EmpId = 1, Name = "Rahul" };//The manager
            Employee Amit = new Employee { EmpId = 2, Name = "Amit" };
            Employee Mohan = new Employee { EmpId = 3, Name = "Mohan" };

            Rahul.AddSubordinate(Amit);
            Rahul.AddSubordinate(Mohan);

            Employee Rita = new Employee { EmpId = 4, Name = "Rita" };
            Employee Hari = new Employee { EmpId = 5, Name = "Hari" };

            Amit.AddSubordinate(Rita);
            Amit.AddSubordinate(Hari);

            Employee Kamal = new Employee { EmpId = 6, Name = "Kamal" };
            Employee Raj = new Employee { EmpId = 7, Name = "Raj" };

            Contractor Sam = new Contractor { EmpId = 8, Name = "Sam" };
            Contractor tim = new Contractor { EmpId = 9, Name = "Tim" };

            Mohan.AddSubordinate(Kamal);
            Mohan.AddSubordinate(Raj);
            Mohan.AddSubordinate(Sam);
            Mohan.AddSubordinate(tim);

            foreach (Employee manager in Rahul)
            {
                var topManager = manager;

                foreach (var employee in manager)
                {
                    var subordinate = employee;

                }
            }


            return View();
        }

        // GET: EmployeeController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

      
        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
      
    }
}

CinemaDemo/Controllers/StreamController.cs
using CinemaDemo.Factories;
using CinemaDemo.Models.PresentationModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CinemaDemo.Controllers
{
    public class StreamController : Controller
    {
        private readonly IStreamFactory streamFactory;

        public StreamController(IStreamFactory streamFactory)
        {
            this.streamFactory = streamFactory;
        }

        public IEnumerable<string> GetMovies(string userSelection)
        {
            return streamFactory.GetStreamService(userSelection).ShowMovies();
        }

        [HttpGet("movies/{userSelection}")]
        public IActionResult Index(string userSelection)
        {
            var viewModel = new StreamingViewModel();
            var filmList = streamFactory.GetStreamService(userSelection).ShowMovies();
            viewModel.FilmsListModel = filmList;

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult GetListings(string userSelection)
        {
            var viewModel = new StreamingViewModel();
            var filmList = streamFactory.GetStreamService(userSelection).ShowMovies();
            viewModel.FilmsListModel = filmList;

            return View("Index", viewModel);
        }
    }
}

CinemaDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CinemaDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CinemaDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Film Listings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Film Listings SQL</a>
                        </li>
                        <li class="nav-item">

                            @Html.ActionLink("Netflix", "GetListings", "Stream", new { userSelection = "Netflix" }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Amazon", "GetListings", "Stream", new { userSelection = "Amazon" }, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Approvals" asp-action="Index">Chain of Responsibility</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CinemaDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>